# Generated by Django 4.2.7 on 2025-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customabstractuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="email_to_change",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customabstractuser",
            name="otp_change_email",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customabstractuser",
            name="otp_expires_change_email",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время жизни otp"
            ),
        ),
    ]
