# Generated by Django 4.2.7 on 2025-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customabstractuser_email_to_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="odkp",
            field=models.CharField(max_length=40, null=True, verbose_name="ОДКП"),
        ),
    ]
