# Generated by Django 4.2.7 on 2025-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customabstractuser_odkp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customabstractuser",
            name="odkp",
        ),
        migrations.AddField(
            model_name="customabstractuser",
            name="okdp",
            field=models.CharField(max_length=40, null=True, verbose_name="ОКДП"),
        ),
    ]
