# Generated by Django 4.2.7 on 2025-12-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_customabstractuser_odkp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="previously_existed",
            field=models.BooleanField(
                default=False, verbose_name="Существовал ли пользователь ранее"
            ),
        ),
    ]
