services:
  db:
    image: postgres:13
    container_name: kaleidoskop_db
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:  
    image: minio/minio
    container_name: kaleidoskop_minio
    restart: unless-stopped  
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - "9000"
    volumes:  
      - minio-storage:/data  
    environment:  
      - MINIO_ROOT_USER=miniouser  
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"  
    healthcheck:  
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]  
      interval: 30s  
      timeout: 20s  
      retries: 3
  
  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: kaleidoskop_rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    # network_mode: "host"
  
  app:
    build: ./kaleidoskop/
    container_name: main_app
    # ports:
    #   - 8080:8000
    depends_on:
      - db
    environment:
      - CONTAINER_LAUNCH=true
    volumes:
      - static:/static/

  celery:
    build: ./kaleidoskop/
    container_name: celery_worker_kaleidoskop
    restart: always
    environment:
      - CONTAINER_LAUNCH=true
    # network_mode: "host"
    depends_on:
      - app
      - rabbitmq
    command: celery -A kaleidoskop worker -l INFO

  elasticsearch:
    image: elasticsearch:8.17.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=MyPassword

  #recommendation system:

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    # network_mode: "host"
    volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - static:/static/

  telegram_bot:
    build: ./Telegram_Notification
    container_name: telegram
    depends_on:
      - redis
      - rabbitmq
    profiles: [donotstart]
  
  recommendation_system:
    build: ./AI_Feature
    container_name: ai_web_app
    ports:
      - 8082:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    profiles: [donotstart]
  
volumes:
 pg_data:
 minio-storage:
 static: