# Generated by Django 4.2.7 on 2025-10-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=25, verbose_name="Имя пользователя"),
                ),
                ("chat_id", models.CharField(max_length=60, verbose_name="ID чата")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время созднания"
                    ),
                ),
            ],
        ),
    ]
