# Generated by Django 4.2.7 on 2025-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Настройки Сайта")),
                (
                    "edited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Последнее изменение"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
