# Generated by Django 4.2.7 on 2025-12-16 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_category_image"),
        ("admin_panel", "0002_sitesettings_delete_telegramuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compilation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Название подборки"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Старт активности"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец активности"
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Активно")),
                (
                    "items",
                    models.ManyToManyField(related_name="compilations", to="api.item"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
