# Generated by Django 4.2.7 on 2025-12-16 09:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_compilation"),
    ]

    operations = [
        migrations.AddField(
            model_name="compilation",
            name="queue",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Очередь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compilation",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Старт активности"
            ),
        ),
    ]
