# Generated by Django 4.2.7 on 2025-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_rename_order_banner_queue"),
        ("admin_panel", "0004_compilation_queue_alter_compilation_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compilation",
            name="items",
        ),
        migrations.AddField(
            model_name="compilation",
            name="nomenclatures",
            field=models.ManyToManyField(
                related_name="compilations", to="api.nomenclature"
            ),
        ),
    ]
