upstream minio_s3 {
    server minio:9000;
}
client_max_body_size 20M;


server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/ssl/mycert.pem;
    ssl_certificate_key /etc/ssl/mykey.pem;

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://app:8000/api/;
    }

    location /static/{
        alias /static/;
    }
    
    location /media/{
        proxy_set_header Host $host;
        proxy_pass_request_headers off;
        proxy_pass http://minio_s3/;
    }
}


server {
    listen 8080;
    server_name _;
    index index.html;

    location /api/ {
        proxy_set_header Host $host;
        # proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://app:8000/api/;
    }

    location /static/    {
        alias /static/;
        try_files $uri $uri/ /index.html;
    }

    location /admin/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://app:8000/admin/;
    }

    location /media/{
        proxy_set_header Host $host;
        proxy_pass_request_headers off;
        proxy_pass http://minio_s3/;
    }
}