"""
Django settings for kaleidoskop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.utils.timezone import timedelta
import django
from django.utils.encoding import force_str
import zoneinfo 
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
django.utils.encoding.force_text = force_str

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SERVER_ENDPOINT = os.getenv("SERVER_ENDPOINT")
ALLOWED_HOSTS = ["localhost", "127.0.0.1", SERVER_ENDPOINT]

CONTAINER_LAUNCHER = os.getenv("CONTAINER_LAUNCH", False)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    # "django_elasticsearch_dsl",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_yasg",
    "users.apps.UsersConfig",
    "api.apps.ApiConfig",
    "receiver.apps.ReceiverConfig",
    "search.apps.SearchConfig",
    "recomendation_system.apps.RecomendationSystemConfig",
    "admin_panel.apps.AdminPanelConfig",
    "django_extensions"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = "users.CustomAbstractUser"
ROOT_URLCONF = "kaleidoskop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kaleidoskop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        # Меняем настройку Django: теперь для работы будет использоваться
        # бэкенд postgresql
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("DB_HOST", 'localhost') if not CONTAINER_LAUNCHER else 'db',
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Yekaterinburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        "users.authenticate.CookieJWTAuthentication"
    ],
}

# File Storage

# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
DEFAULT_FILE_STORAGE = "kaleidoskop.storage.MinioDualStorage"

AWS_STORAGE_BUCKET_NAME = "local"
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_ADDRESSING_STYLE = "path"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "pyamqp://guest@localhost//") if not CONTAINER_LAUNCHER else "pyamqp://guest@rabbitmq//"  # Когда пакуешь в контейнер поменять localhost->rabbitmq
BROKER_URL = os.getenv("BROKER_URL", "pyamqp://guest@localhost:5672//") if not CONTAINER_LAUNCHER else "pyamqp://guest@rabbitmq:5672//" # Когда пакуешь в контейнер поменять localhost->rabbitmq

API_KEY_1C = "XDXDRJAKARJKA1234SIE5$"
USER_1C = os.getenv("USER_1C")
PASSWORD_1C = os.getenv("PASSWORD_1C")
SERVER_1C = "http://localhost/demohttp/hs/apiv1" if not CONTAINER_LAUNCHER else f"http://{os.getenv('REMOTE_1C')}/demohttp/hs/apiv1"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

SIMPLE_JWT = {
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),

    "REFRESH_COOKIE": 'refresh_token',
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'None',
    'REFRESH_COOKIE_SAMESITE': 'None',
    'REFRESH_COOKE_SECURE': True
}

# ELASTICSEARCH_DSL = {
#     "default": {
#         "hosts": "http://localhost:9200" if not CONTAINER_LAUNCHER else "http://elasticsearch:9200",
#         "http_auth": ("elastic", "MyPassword"),
#         "verify_certs": False,
#         "ca_certs": None,
#     }
# }

LANGUAGE_CODE = 'ru-RU'

STATIC_URL = "/static/"
STATIC_ROOT = "/static/"

REDIS_HOST = "localhost" if not CONTAINER_LAUNCHER else "redis"

RABBIT_MQ_USER = os.getenv("RABBIT_MQ_USER")
RABBIT_MQ_PASSWORD = os.getenv("RABBIT_MQ_PASSWORD")
RABBIT_MQ_HOST = "localhost" if not CONTAINER_LAUNCHER else "rabbitmq"


CORS_ORIGIN_ALLOW_ALL = True
CORS_URLS_REGEX = r"^/.*$"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") #only prod
SECURE_SSL_REDIRECT = False

CSRF_TRUSTED_ORIGINS = [
    f"https://{SERVER_ENDPOINT}:8000",
    f"https://{SERVER_ENDPOINT}",
    "http://localhost:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]# костыль
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using the Bearer scheme. Example: 'Bearer {token}'",
        }
    },
    "DEFAULT_INFO": "api.urls.api_info",
    'DEFAULT_AUTO_SCHEMA_CLASS': 'api.swagger.UrlBasedTagsSchema'
    # другие опции...
}
LOCAL_TZ = zoneinfo.ZoneInfo('Asia/Yekaterinburg')
RECOMENDATIONS_URL = "localhost:8082" if not CONTAINER_LAUNCHER else "recommendation_system:8000"

CORS_ALLOW_CREDENTIALS = True