# Generated by Django 3.2 on 2025-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20250724_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="item",
            name="article",
            field=models.CharField(max_length=20, unique=True, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Код"),
        ),
    ]
