# Generated by Django 3.2 on 2025-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250724_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Код родителя'),
        ),
    ]
