# Generated by Django 3.2 on 2025-07-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_category_parent_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="UOM",
            field=models.CharField(
                max_length=5, null=True, verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="parent_code",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Код родителя"
            ),
        ),
    ]
