# Generated by Django 3.2 on 2025-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20250730_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="country",
            field=models.CharField(
                max_length=25, null=True, verbose_name="Страна-производитель"
            ),
        ),
    ]
