# Generated by Django 3.2 on 2025-07-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_item_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="items",
                to="api.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
