# Generated by Django 3.2 on 2025-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=40, unique=True, verbose_name='Артикул'),
        ),
    ]
