# Generated by Django 4.1 on 2025-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_item_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="article",
            field=models.CharField(max_length=40, unique=True, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Код"),
        ),
    ]
