# Generated by Django 4.1 on 2025-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_item_article_alter_item_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Доступен публично"),
        ),
    ]
