# Generated by Django 4.2.7 on 2025-08-08 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_cart_user_comment_user_like_user_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "custom_name",
                    models.CharField(
                        max_length=50, verbose_name="Пользовательское название"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Remains",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Количество")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remains",
                        to="api.item",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remains",
                        to="api.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
