# Generated by Django 4.2.7 on 2025-08-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_warehouse_remains"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="production_country",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="remains",
            name="count",
            field=models.FloatField(verbose_name="Количество"),
        ),
    ]
