# Generated by Django 4.2.7 on 2025-09-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_item_category_nomenclature_item_nomenclature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="code",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent_code",
        ),
    ]
