# Generated by Django 4.2.7 on 2025-09-11 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_category_code_remove_category_parent_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="NomenclatureCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="api.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomenclatures",
                        to="api.nomenclature",
                        verbose_name="Номенклатура",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
