# Generated by Django 4.2.7 on 2025-09-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_nomenclaturecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="nomenclatures",
            field=models.ManyToManyField(
                related_name="nomenclatures",
                through="api.NomenclatureCategory",
                to="api.nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclaturecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclaturecategory",
            name="nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.nomenclature",
                verbose_name="Номенклатура",
            ),
        ),
    ]
