# Generated by Django 4.2.7 on 2025-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_category_nomenclatures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories",
                through="api.NomenclatureCategory",
                to="api.category",
            ),
        ),
    ]
