# Generated by Django 4.2.7 on 2025-10-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_nomenclature_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=100, verbose_name="Адрес"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address_latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="Широта"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="address_longtitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="Долгота"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.TextField(
                choices=[("Самовывоз", "Self Pickup"), ("Доставка", "Delivery")],
                default="Самовывоз",
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.TextField(
                choices=[
                    ("Наличными", "Cash"),
                    ("Картой", "Credit Card"),
                    ("Онлайн", "Online"),
                ],
                default="Онлайн",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[
                    ("На согласовании", "On Approve"),
                    ("Согласован", "Approved"),
                    ("На реализации", "On Realisation"),
                    ("Реализован", "Realised"),
                ],
                default="На согласовании",
                verbose_name="Статус",
            ),
        ),
    ]
