# Generated by Django 4.2.7 on 2025-10-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_order_address_order_address_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="bought",
            new_name="currently_for_order",
        ),
    ]
