# Generated by Django 4.2.7 on 2025-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_rename_bought_cart_currently_for_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="currently_for_order",
            new_name="bought",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="marked_for_order",
            field=models.BooleanField(
                default=False, verbose_name="Помечено для заказа"
            ),
        ),
    ]
