# Generated by Django 4.2.7 on 2025-10-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_currently_for_order_cart_bought_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Товары в корзинах",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Избранное", "verbose_name_plural": "Избранное"},
        ),
        migrations.AlterModelOptions(
            name="nomenclature",
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
            },
        ),
        migrations.AlterModelOptions(
            name="nomenclaturecategory",
            options={
                "verbose_name": "Номенклатура<->Категория",
                "verbose_name_plural": "Номенклатуры<->Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="remains",
            options={"verbose_name": "Остаток", "verbose_name_plural": "Остатки"},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "Склад", "verbose_name_plural": "Склады"},
        ),
    ]
