# Generated by Django 4.2.7 on 2025-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address_latitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address_longtitude",
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=100, null=True, verbose_name="Адрес"),
        ),
    ]
