# Generated by Django 4.2.7 on 2025-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_remove_order_address_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(max_length=500, null=True, verbose_name="Описание"),
        ),
    ]
