# Generated by Django 4.2.7 on 2025-11-25 14:48

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_item_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("source", models.ImageField(upload_to="media")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="amount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
