# Generated by Django 4.2.7 on 2025-11-26 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_itemimage_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Название")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Единица измерения",
                    ),
                ),
                ("value", models.TextField(max_length=200, verbose_name="Значение")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="item",
            name="parameters",
            field=models.ManyToManyField(
                null=True,
                related_name="items",
                to="api.parameter",
                verbose_name="Параметры",
            ),
        ),
    ]
