# Generated by Django 4.2.7 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_parameter_item_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parameters",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="items",
                to="api.parameter",
                verbose_name="Параметры",
            ),
        ),
    ]
