# Generated by Django 4.2.7 on 2025-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_item_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
