# Generated by Django 4.2.7 on 2025-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_parameter_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="unit",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Единица измерения"
            ),
        ),
    ]
