# Generated by Django 4.2.7 on 2025-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_parameter_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="source",
            field=models.ImageField(max_length=300, upload_to="media"),
        ),
    ]
