# Generated by Django 4.2.7 on 2025-11-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_itemimage_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="bought",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="api.order",
                verbose_name="Заказ",
            ),
        ),
    ]
