# Generated by Django 4.2.7 on 2025-11-27 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_cart_bought_remove_order_cart_cart_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="value",
        ),
        migrations.CreateModel(
            name="ParameterItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(max_length=200, verbose_name="Значение")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="api.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.parameter",
                        verbose_name="Параметр",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
