# Generated by Django 4.2.7 on 2025-11-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_brand_remove_item_parameters_remove_parameter_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.brand",
                verbose_name="Брэнд",
            ),
        ),
    ]
