# Generated by Django 4.2.7 on 2025-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_item_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="okdp",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ОКДП"
            ),
        ),
    ]
