# Generated by Django 4.2.7 on 2025-12-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_item_okdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[
                    ("На согласовании", "On Approve"),
                    ("Согласован", "Approved"),
                    ("На реализации", "On Realisation"),
                    ("Реализован", "Realised"),
                    ("Отменен", "Canceled"),
                ],
                default="На согласовании",
                verbose_name="Статус",
            ),
        ),
    ]
