# Generated by Django 4.2.7 on 2025-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_order_address_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(
                default=None, max_length=50, unique=True, verbose_name="Штрихкод"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="price_group",
            field=models.CharField(
                choices=[
                    ("Без скидки", "Nothing"),
                    ("Ценовая группа 1%", "First"),
                    ("Ценовая группа 2%", "Second"),
                    ("Ценовая группа 3%", "Third"),
                    ("Ценовая группа 4%", "Fourth"),
                    ("Ценовая группа 5%", "Fifth"),
                ],
                default="Без скидки",
                max_length=50,
                verbose_name="Ценновая группа",
            ),
        ),
    ]
