# Generated by Django 4.2.7 on 2025-12-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_item_barcode_item_price_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Штрихкод"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_group",
            field=models.CharField(
                choices=[
                    ("Без скидки", "Nothing"),
                    ("Ценовая группа 1%", "First"),
                    ("Ценовая группа 2%", "Second"),
                    ("Ценовая группа 3%", "Third"),
                    ("Ценовая группа 4%", "Fourth"),
                    ("Ценовая группа 5%", "Fifth"),
                ],
                default="Без скидки",
                max_length=100,
                verbose_name="Ценновая группа",
            ),
        ),
    ]
