# Generated by Django 4.2.7 on 2025-12-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_item_barcode_alter_item_price_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[
                    ("Отправлен", "Sended"),
                    ("На согласовании", "On Approve"),
                    ("Согласован", "Approved"),
                    ("На реализации", "On Realisation"),
                    ("Реализован", "Realised"),
                    ("Отменен", "Canceled"),
                ],
                default="Отправлен",
                verbose_name="Статус",
            ),
        ),
    ]
