# Generated by Django 4.2.7 on 2025-12-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
    ]
