# Generated by Django 4.2.7 on 2025-12-11 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_order_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("source", models.ImageField(max_length=255, upload_to="banners")),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название баннера"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
