# Generated by Django 4.2.7 on 2025-12-11 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="banner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="group_type",
            field=models.TextField(
                choices=[("FIRST", "First"), ("SECOND", "Second")],
                default="FIRST",
                verbose_name="Группа банера",
            ),
            preserve_default=False,
        ),
    ]
