# Generated by Django 4.2.7 on 2025-12-12 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_banner_active_banner_created_at_banner_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="order",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Порядок",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="banner",
            unique_together={("order", "group_type")},
        ),
    ]
