# Generated by Django 4.2.7 on 2025-12-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_banner_order_alter_banner_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="title",
        ),
    ]
