# Generated by Django 4.2.7 on 2025-12-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_remove_banner_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="banner",
            unique_together=set(),
        ),
    ]
