# Generated by Django 4.2.7 on 2025-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_alter_banner_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активно"),
        ),
    ]
