# Generated by Django 4.2.7 on 2025-12-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_category_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                null=True, upload_to="categories", verbose_name="Картинка"
            ),
        ),
    ]
