# Generated by Django 4.2.7 on 2025-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_category_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="order",
            new_name="queue",
        ),
    ]
