# Generated by Django 4.2.7 on 2025-12-23 09:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_order_banner_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='categories', validators=[api.models.validate_svg], verbose_name='Картинка'),
        ),
    ]
