# Generated by Django 4.2.7 on 2026-01-04 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclaturecategory',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='categories', verbose_name='Картинка'),
        ),
    ]
