# Generated by Django 4.2.7 on 2026-01-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_nomenclaturecategory_created_at_alter_category_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomenclaturecategory',
            unique_together={('nomenclature', 'category')},
        ),
    ]
