# Generated by Django 4.2.7 on 2026-03-17 10:59

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_nomenclaturecategory_unique_together'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL("""
                          CREATE INDEX idx_api_item_title_trgm
                          ON api_item USING gin (lower(title) gin_trgm_ops);
                          """,
                          reverse_sql="DROP INDEX IF EXISTS idx_api_item_title_trgm;"
                          )
    ]
