# Generated by Django 4.2.7 on 2026-03-18 09:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_item_api_item_title_79b323_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_item_search__c71c22_gin'),
        ),
    ]
