# Generated by Django 4.2.7 on 2026-03-20 08:41

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_item_search_vector_item_title_trgm_gin_ops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='associative',
            field=models.BooleanField(default=False, verbose_name='Ассоциативная номенклатура'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='imported',
            field=models.BooleanField(default=True, verbose_name='Импортированно из 1С'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm_gin_ops', opclasses=['gin_trgm_ops']),
        ),
    ]
