# Generated by Django 4.2.7 on 2026-04-17 08:41

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_nomenclature_associative_nomenclature_imported_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default="", max_length=200, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.CharField(
                default="", max_length=200, verbose_name="Слаг названия"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["slug"], name="api_categor_slug_c53926_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["slug"], name="api_item_slug_8b7dd6_btree"
            ),
        ),
    ]
