# Generated by Django 4.2.7 on 2026-06-01 08:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["article"], name="api_item_article_b009f4_btree"
            ),
        ),
    ]
